import { VpnConfig } from '../types';

export const SAMPLE_SERVERS: VpnConfig[] = [
  {
    id: 'config-ssh-ws',
    name: 'SSH WebSocket Custom',
    protocol: 'ssh_ws',
    server: '104.21.45.1',
    port: 80,
    flag: '⚡',
    country: 'Custom Server',
    ping: 24,
    load: 42,
    isPremium: true,
    sshUser: 'user_vpn',
    sshPassword: 'password123',
    bugHost: 'cdn.cloudflare.com',
    sni: 'cdn.cloudflare.com',
    wsPath: '/ssh-ws',
    payload: 'GET / HTTP/1.1[crlf]Host: cdn.cloudflare.com[crlf]Upgrade: websocket[crlf]Connection: Upgrade[crlf][crlf]',
    autoPing: true,
    enableDns: true,
    forwardUdp: true,
    wakeLock: true,
  },
  {
    id: 'config-ssh-ssl',
    name: 'SSH SSL / TLS Direct',
    protocol: 'ssh_ssl',
    server: '104.21.45.2',
    port: 443,
    flag: '🔒',
    country: 'Custom Server',
    ping: 30,
    load: 25,
    isPremium: false,
    sshUser: 'user_ssl',
    sshPassword: 'password123',
    sni: 'm.domain.com',
    bugHost: 'm.domain.com',
    payload: 'CONNECT [host_port] HTTP/1.1[crlf]Host: m.domain.com[crlf][crlf]',
    autoPing: true,
    enableDns: true,
    forwardUdp: true,
    wakeLock: true,
  },
  {
    id: 'config-v2ray',
    name: 'V2Ray / Xray Reality',
    protocol: 'v2ray_xray',
    server: '104.21.45.3',
    port: 443,
    flag: '⚡',
    country: 'Custom Server',
    ping: 35,
    load: 30,
    isPremium: true,
    v2rayType: 'vless',
    uuid: '9f8e7d6c-5b4a-3f2e-1d0c-9b8a7f6e5d4c',
    security: 'reality',
    network: 'grpc',
    v2rayPath: 'vless-grpc',
    v2rayTls: true,
    sni: 'cdn.auth.cloudflare.com',
    autoPing: true,
    enableDns: true,
    forwardUdp: true,
    wakeLock: true,
  },
  {
    id: 'config-slowdns',
    name: 'SlowDNS / DNSTT',
    protocol: 'slowdns',
    server: '8.8.8.8',
    port: 53,
    flag: '📡',
    country: 'DNS Resolver',
    ping: 60,
    load: 20,
    isPremium: false,
    dnsPubKey: 'e8f7a6b5c4d3e2f10987654321abcdef0123456789abcdef0123456789abcdef',
    dnsNameServer: 'ns1.yourdomain.com',
    dnsTargetResolver: '8.8.8.8',
    dnsMode: 'TXT',
    dnsMtu: 1230,
    autoPing: true,
    enableDns: true,
    forwardUdp: true,
    wakeLock: true,
  },
  {
    id: 'config-hy2',
    name: 'Hysteria v2 (UDP Obfs)',
    protocol: 'hysteria_v2',
    server: '104.21.45.4',
    port: 443,
    flag: '🚀',
    country: 'Custom Server',
    ping: 28,
    load: 40,
    isPremium: true,
    hysteriaVersion: 2,
    authPassword: 'hy2_secret_auth_pass',
    portHopping: '20000-50000',
    obfsKey: 'salamander_key',
    obfsType: 'salamander',
    upMbps: 100,
    downMbps: 200,
    alpn: 'h3',
    sni: 'cloudflare.com',
    autoPing: true,
    enableDns: true,
    forwardUdp: true,
    wakeLock: true,
  },
  {
    id: 'config-hy1',
    name: 'Hysteria v1 Fast UDP',
    protocol: 'hysteria_v1',
    server: '104.21.45.5',
    port: 36712,
    flag: '🔥',
    country: 'Custom Server',
    ping: 45,
    load: 28,
    isPremium: false,
    hysteriaVersion: 1,
    authPassword: 'hy1_token_pass',
    obfsKey: 'obfs_key',
    upMbps: 50,
    downMbps: 100,
    alpn: 'h3',
    sni: 'cloudflare.com',
    autoPing: true,
    enableDns: true,
    forwardUdp: true,
    wakeLock: true,
  },
  {
    id: 'config-udpcustom',
    name: 'UDP Custom GW 7300',
    protocol: 'udp_custom',
    server: '104.21.45.6',
    port: 7300,
    flag: '🎮',
    country: 'Custom Server',
    ping: 32,
    load: 45,
    isPremium: true,
    udpGwServer: '104.21.45.6:7300',
    udpGwPort: 7300,
    udpHeaderPayload: 'UDP-CUSTOM-HEADER v2.4\r\nHost: domain.com\r\n\r\n',
    udpBuffer: 8192,
    udpMtu: 1400,
    autoPing: true,
    enableDns: true,
    forwardUdp: true,
    wakeLock: true,
  },
  {
    id: 'config-zivpn',
    name: 'ZiVPN UDP / SSL',
    protocol: 'zivpn',
    server: '104.21.45.7',
    port: 5666,
    flag: '⚡',
    country: 'Custom Server',
    ping: 29,
    load: 20,
    isPremium: true,
    ziKey: 'zi_key_custom',
    ziPort: 5666,
    ziPass: 'zivpn_pass',
    ziMode: 'udp',
    ziPayload: 'GET /zivpn HTTP/1.1\r\nHost: domain.com\r\nUpgrade: zivpn\r\n\r\n',
    autoPing: true,
    enableDns: true,
    forwardUdp: true,
    wakeLock: true,
  },
];
